/**
 * Indian States and Major Cities Mapping for Location Selector
 * Includes all 28 States & 8 Union Territories sorted A-Z,
 * with cities under each state sorted in alphabetical A-Z order.
 */

export interface IndianStateLocation {
  state: string;
  cities: string[];
}

export const INDIAN_STATES_AND_CITIES: IndianStateLocation[] = [
  {
    state: 'Andaman and Nicobar Islands',
    cities: ['Car Nicobar', 'Diglipur', 'Mayabunder', 'Port Blair', 'Rangat'],
  },
  {
    state: 'Andhra Pradesh',
    cities: [
      'Anantapur',
      'Chittoor',
      'Eluru',
      'Guntur',
      'Kadapa',
      'Kakinada',
      'Kurnool',
      'Machilipatnam',
      'Nellore',
      'Ongole',
      'Rajahmundry',
      'Srikakulam',
      'Tirupati',
      'Vijayawada',
      'Visakhapatnam',
      'Vizianagaram',
    ],
  },
  {
    state: 'Arunachal Pradesh',
    cities: ['Itanagar', 'Naharlagun', 'Pasighat', 'Tawang', 'Tezu'],
  },
  {
    state: 'Assam',
    cities: [
      'Bongaigaon',
      'Dibrugarh',
      'Guwahati',
      'Jorhat',
      'Nagaon',
      'Silchar',
      'Tezpur',
      'Tinsukia',
    ],
  },
  {
    state: 'Bihar',
    cities: [
      'Arrah',
      'Begusarai',
      'Bettiah',
      'Bhagalpur',
      'Bihar Sharif',
      'Chhapra',
      'Darbhanga',
      'Gaya',
      'Hajipur',
      'Katihar',
      'Madhubani',
      'Motihari',
      'Munger',
      'Muzaffarpur',
      'Patna',
      'Purnia',
      'Saharsa',
      'Samastipur',
      'Sasaram',
      'Sitamarhi',
      'Siwan',
    ],
  },
  {
    state: 'Chandigarh',
    cities: ['Chandigarh'],
  },
  {
    state: 'Chhattisgarh',
    cities: [
      'Bhilai',
      'Bilaspur',
      'Durg',
      'Jagdalpur',
      'Korba',
      'Raigarh',
      'Raipur',
      'Rajnandgaon',
    ],
  },
  {
    state: 'Dadra and Nagar Haveli and Daman and Diu',
    cities: ['Daman', 'Diu', 'Silvassa'],
  },
  {
    state: 'Delhi (NCR)',
    cities: [
      'Delhi',
      'Faridabad',
      'Ghaziabad',
      'Greater Noida',
      'Gurugram (Gurgaon)',
      'New Delhi',
      'Noida',
    ],
  },
  {
    state: 'Goa',
    cities: ['Mapusa', 'Margao', 'Panaji', 'Ponda', 'Vasco da Gama'],
  },
  {
    state: 'Gujarat',
    cities: [
      'Ahmedabad',
      'Anand',
      'Bharuch',
      'Bhavnagar',
      'Bhuj',
      'Dahod',
      'Gandhidham',
      'Gandhinagar',
      'Godhra',
      'Jamnagar',
      'Junagadh',
      'Mehsana',
      'Morbi',
      'Nadiad',
      'Navsari',
      'Palanpur',
      'Patan',
      'Porbandar',
      'Rajkot',
      'Surat',
      'Surendranagar',
      'Vadodara',
      'Valsad',
      'Vapi',
    ],
  },
  {
    state: 'Haryana',
    cities: [
      'Ambala',
      'Bhiwani',
      'Faridabad',
      'Gurugram (Gurgaon)',
      'Hisar',
      'Jhind',
      'Karnal',
      'Panchkula',
      'Panipat',
      'Rewari',
      'Rohtak',
      'Sirsa',
      'Sonipat',
      'Yamunanagar',
    ],
  },
  {
    state: 'Himachal Pradesh',
    cities: [
      'Baddi',
      'Dharamshala',
      'Hamirpur',
      'Kullu',
      'Mandi',
      'Shimla',
      'Solan',
    ],
  },
  {
    state: 'Jammu & Kashmir',
    cities: [
      'Anantnag',
      'Baramulla',
      'Jammu',
      'Kathua',
      'Srinagar',
      'Udhampur',
    ],
  },
  {
    state: 'Jharkhand',
    cities: [
      'Bokaro Steel City',
      'Deoghar',
      'Dhanbad',
      'Giridih',
      'Hazaribagh',
      'Jamshedpur',
      'Ranchi',
    ],
  },
  {
    state: 'Karnataka',
    cities: [
      'Ballari (Bellary)',
      'Belagavi (Belgaum)',
      'Bengaluru (Bangalore)',
      'Davanagere',
      'Hubballi-Dharwad',
      'Kalaburagi (Gulbarga)',
      'Mangaluru (Mangalore)',
      'Mysuru (Mysore)',
      'Shivamogga (Shimoga)',
      'Tumakuru (Tumkur)',
      'Vijayapura (Bijapur)',
    ],
  },
  {
    state: 'Kerala',
    cities: [
      'Alappuzha',
      'Kannur',
      'Kochi (Cochin)',
      'Kollam',
      'Kottayam',
      'Kozhikode (Calicut)',
      'Palakkad',
      'Thiruvananthapuram (Trivandrum)',
      'Thrissur',
    ],
  },
  {
    state: 'Ladakh',
    cities: ['Kargil', 'Leh'],
  },
  {
    state: 'Lakshadweep',
    cities: ['Kavaratti'],
  },
  {
    state: 'Madhya Pradesh',
    cities: [
      'Bhopal',
      'Burhanpur',
      'Chhatarpur',
      'Chhindwara',
      'Damoh',
      'Datia',
      'Dewas',
      'Dhar',
      'Gwalior',
      'Indore',
      'Jabalpur',
      'Katni',
      'Mandsaur',
      'Morena',
      'Neemuch',
      'Ratlam',
      'Rewa',
      'Sagar',
      'Satna',
      'Sehore',
      'Singrauli',
      'Ujjain',
      'Vidisha',
    ],
  },
  {
    state: 'Maharashtra',
    cities: [
      'Ahmednagar',
      'Akola',
      'Amravati',
      'Chhatrapati Sambhajinagar (Aurangabad)',
      'Dhule',
      'Jalgaon',
      'Kalyan-Dombivli',
      'Kolhapur',
      'Latur',
      'Malegaon',
      'Mira-Bhayandar',
      'Mumbai',
      'Nagpur',
      'Nanded',
      'Nashik',
      'Navi Mumbai',
      'Panvel',
      'Parbhani',
      'Pimpri-Chinchwad',
      'Pune',
      'Sangli',
      'Satara',
      'Solapur',
      'Thane',
      'Ulhasnagar',
      'Vasai-Virar',
    ],
  },
  {
    state: 'Manipur',
    cities: ['Bishnupur', 'Churachandpur', 'Imphal', 'Thoubal'],
  },
  {
    state: 'Meghalaya',
    cities: ['Jowai', 'Nongpoh', 'Shillong', 'Tura'],
  },
  {
    state: 'Mizoram',
    cities: ['Aizawl', 'Champhai', 'Lunglei', 'Serchhip'],
  },
  {
    state: 'Nagaland',
    cities: ['Dimapur', 'Kohima', 'Mokokchung', 'Tuensang'],
  },
  {
    state: 'Odisha',
    cities: [
      'Balasore',
      'Berhampur',
      'Bhadrak',
      'Bhubaneswar',
      'Cuttack',
      'Jharsuguda',
      'Puri',
      'Rourkela',
      'Sambalpur',
    ],
  },
  {
    state: 'Puducherry',
    cities: ['Karaikal', 'Mahe', 'Puducherry', 'Yanam'],
  },
  {
    state: 'Punjab',
    cities: [
      'Amritsar',
      'Batala',
      'Bathinda',
      'Hoshiarpur',
      'Jalandhar',
      'Ludhiana',
      'Moga',
      'Mohali (SAS Nagar)',
      'Pathankot',
      'Patiala',
    ],
  },
  {
    state: 'Rajasthan',
    cities: [
      'Ajmer',
      'Alwar',
      'Banswara',
      'Barmer',
      'Bharatpur',
      'Bhilwara',
      'Bikaner',
      'Chittorgarh',
      'Churu',
      'Dausa',
      'Ganganagar',
      'Hanumangarh',
      'Jaipur',
      'Jaisalmer',
      'Jalore',
      'Jhalawar',
      'Jhunjhunu',
      'Jodhpur',
      'Kota',
      'Nagaur',
      'Pali',
      'Pratapgarh',
      'Rajsamand',
      'Sawai Madhopur',
      'Sikar',
      'Sirohi',
      'Tonk',
      'Udaipur',
    ],
  },
  {
    state: 'Sikkim',
    cities: ['Gangtok', 'Gyalshing', 'Mangan', 'Namchi'],
  },
  {
    state: 'Tamil Nadu',
    cities: [
      'Chennai',
      'Coimbatore',
      'Cuddalore',
      'Dindigul',
      'Erode',
      'Kanchipuram',
      'Karur',
      'Madurai',
      'Nagercoil',
      'Salem',
      'Thanjavur',
      'Tiruchirappalli (Trichy)',
      'Tirunelveli',
      'Tiruppur',
      'Tuticorin (Thoothukudi)',
      'Vellore',
    ],
  },
  {
    state: 'Telangana',
    cities: [
      'Hyderabad',
      'Karimnagar',
      'Khammam',
      'Mahbubnagar',
      'Nalgonda',
      'Nizamabad',
      'Ramagundam',
      'Siddipet',
      'Suryapet',
      'Warangal',
    ],
  },
  {
    state: 'Tripura',
    cities: ['Agartala', 'Dharmanagar', 'Kailashahar', 'Udaipur'],
  },
  {
    state: 'Uttar Pradesh',
    cities: [
      'Agra',
      'Aligarh',
      'Amroha',
      'Ayodhya',
      'Azamgarh',
      'Bahraich',
      'Ballia',
      'Banda',
      'Bareilly',
      'Basti',
      'Bijnor',
      'Bulandshahr',
      'Deoria',
      'Etah',
      'Etawah',
      'Farrukhabad',
      'Fatehabad',
      'Fatehpur',
      'Firozabad',
      'Gautam Buddha Nagar',
      'Ghaziabad',
      'Ghazipur',
      'Gonda',
      'Gorakhpur',
      'Hapur',
      'Hardoi',
      'Hathras',
      'Jaunpur',
      'Jhansi',
      'Kannauj',
      'Kanpur',
      'Kasganj',
      'Lakhimpur Kheri',
      'Lalitpur',
      'Lucknow',
      'Mathura',
      'Mau',
      'Meerut',
      'Mirzapur',
      'Moradabad',
      'Muzaffarnagar',
      'Noida',
      'Orai',
      'Pilibhit',
      'Prayagraj (Allahabad)',
      'Rae Bareli',
      'Rampur',
      'Saharanpur',
      'Shahjahanpur',
      'Sitapur',
      'Sultanpur',
      'Unnao',
      'Varanasi',
    ],
  },
  {
    state: 'Uttarakhand',
    cities: [
      'Dehradun',
      'Haldwani',
      'Haridwar',
      'Kashipur',
      'Rishikesh',
      'Roorkee',
      'Rudrapur',
    ],
  },
  {
    state: 'West Bengal',
    cities: [
      'Asansol',
      'Baharampur',
      'Bardhaman',
      'Durgapur',
      'Habra',
      'Howrah',
      'Kharagpur',
      'Kolkata',
      'Malda',
      'Siliguri',
    ],
  },
];

/**
 * Helper to get all Indian States/UTs in alphabetical A-Z order
 */
export function getSortedStates(): string[] {
  return INDIAN_STATES_AND_CITIES.map((s) => s.state).sort((a, b) =>
    a.localeCompare(b)
  );
}

/**
 * Helper to get cities for a state in alphabetical A-Z order
 */
export function getCitiesForState(stateName: string): string[] {
  if (!stateName) return [];
  const found = INDIAN_STATES_AND_CITIES.find(
    (item) => item.state.toLowerCase() === stateName.toLowerCase()
  );
  if (!found) return [];
  return [...found.cities].sort((a, b) => a.localeCompare(b));
}
