/**
 * Indian States and Major Cities Mapping for Location Selector
 */

export interface IndianStateLocation {
  state: string;
  cities: string[];
}

export const INDIAN_STATES_AND_CITIES: IndianStateLocation[] = [
  {
    state: 'Gujarat',
    cities: [
      'Surat',
      'Ahmedabad',
      'Vadodara',
      'Rajkot',
      'Bhavnagar',
      'Jamnagar',
      'Junagadh',
      'Gandhinagar',
      'Anand',
      'Navsari',
      'Vapi',
      'Valsad',
      'Bharuch',
      'Morbi',
      'Mehsana',
      'Nadiad',
      'Porbandar',
      'Godhra',
      'Patan',
      'Surendranagar',
    ],
  },
  {
    state: 'Maharashtra',
    cities: [
      'Mumbai',
      'Pune',
      'Nagpur',
      'Thane',
      'Pimpri-Chinchwad',
      'Nashik',
      'Kalyan-Dombivli',
      'Vasai-Virar',
      'Chhatrapati Sambhajinagar (Aurangabad)',
      'Navi Mumbai',
      'Solapur',
      'Mira-Bhayandar',
      'Bhiwandi',
      'Amravati',
      'Nanded',
      'Kolhapur',
      'Ulhasnagar',
      'Sangli',
      'Jalgaon',
      'Akola',
    ],
  },
  {
    state: 'Delhi (NCR)',
    cities: [
      'New Delhi',
      'Delhi',
      'Noida',
      'Greater Noida',
      'Gurugram (Gurgaon)',
      'Ghaziabad',
      'Faridabad',
    ],
  },
  {
    state: 'Uttar Pradesh',
    cities: [
      'Lucknow',
      'Kanpur',
      'Agra',
      'Varanasi',
      'Meerut',
      'Prayagraj (Allahabad)',
      'Bareilly',
      'Aligarh',
      'Moradabad',
      'Saharanpur',
      'Gorakhpur',
      'Noida',
      'Ghaziabad',
      'Jhansi',
      'Mathura',
      'Ayodhya',
      'Muzaffarnagar',
      'Firozabad',
    ],
  },
  {
    state: 'Rajasthan',
    cities: [
      'Jaipur',
      'Jodhpur',
      'Kota',
      'Bikaner',
      'Ajmer',
      'Udaipur',
      'Bhilwara',
      'Alwar',
      'Sikar',
      'Sri Ganganagar',
      'Pali',
      'Bharatpur',
    ],
  },
  {
    state: 'Karnataka',
    cities: [
      'Bengaluru (Bangalore)',
      'Mysuru (Mysore)',
      'Hubballi-Dharwad',
      'Mangaluru (Mangalore)',
      'Belagavi (Belgaum)',
      'Kalaburagi (Gulbarga)',
      'Davanagere',
      'Ballari (Bellary)',
      'Vijayapura (Bijapur)',
      'Shivamogga (Shimoga)',
      'Tumakuru (Tumkur)',
    ],
  },
  {
    state: 'Tamil Nadu',
    cities: [
      'Chennai',
      'Coimbatore',
      'Madurai',
      'Tiruchirappalli (Trichy)',
      'Salem',
      'Tiruppur',
      'Erode',
      'Vellore',
      'Tirunelveli',
      'Thanjavur',
      'Tuticorin (Thoothukudi)',
      'Dindigul',
    ],
  },
  {
    state: 'Telangana',
    cities: [
      'Hyderabad',
      'Warangal',
      'Nizamabad',
      'Karimnagar',
      'Ramagundam',
      'Khammam',
      'Mahbubnagar',
      'Nalgonda',
      'Siddipet',
    ],
  },
  {
    state: 'West Bengal',
    cities: [
      'Kolkata',
      'Howrah',
      'Asansol',
      'Siliguri',
      'Durgapur',
      'Bardhaman',
      'Malda',
      'Baharampur',
      'Habra',
      'Kharagpur',
    ],
  },
  {
    state: 'Bihar',
    cities: [
      'Patna',
      'Gaya',
      'Bhagalpur',
      'Muzaffarpur',
      'Purnia',
      'Darbhanga',
      'Bihar Sharif',
      'Arrah',
      'Begusarai',
      'Katihar',
    ],
  },
  {
    state: 'Madhya Pradesh',
    cities: [
      'Indore',
      'Bhopal',
      'Jabalpur',
      'Gwalior',
      'Ujjain',
      'Sagar',
      'Dewas',
      'Satna',
      'Ratlam',
      'Rewa',
      'Katni',
      'Singrauli',
    ],
  },
  {
    state: 'Punjab',
    cities: [
      'Ludhiana',
      'Amritsar',
      'Jalandhar',
      'Patiala',
      'Bathinda',
      'Mohali (SAS Nagar)',
      'Pathankot',
      'Hoshiarpur',
      'Batala',
      'Moga',
    ],
  },
  {
    state: 'Haryana',
    cities: [
      'Faridabad',
      'Gurugram (Gurgaon)',
      'Panipat',
      'Ambala',
      'Yamunanagar',
      'Rohtak',
      'Hisar',
      'Karnal',
      'Sonipat',
      'Panchkula',
    ],
  },
  {
    state: 'Kerala',
    cities: [
      'Thiruvananthapuram (Trivandrum)',
      'Kochi (Cochin)',
      'Kozhikode (Calicut)',
      'Thrissur',
      'Kollam',
      'Palakkad',
      'Alappuzha',
      'Kannur',
      'Kottayam',
    ],
  },
  {
    state: 'Andhra Pradesh',
    cities: [
      'Visakhapatnam',
      'Vijayawada',
      'Guntur',
      'Nellore',
      'Kurnool',
      'Kakinada',
      'Rajahmundry',
      'Tirupati',
      'Kadapa',
      'Anantapur',
      'Eluru',
    ],
  },
  {
    state: 'Odisha',
    cities: [
      'Bhubaneswar',
      'Cuttack',
      'Rourkela',
      'Berhampur',
      'Sambalpur',
      'Puri',
      'Balasore',
      'Bhadrak',
    ],
  },
  {
    state: 'Assam',
    cities: [
      'Guwahati',
      'Silchar',
      'Dibrugarh',
      'Jorhat',
      'Nagaon',
      'Tinsukia',
      'Tezpur',
    ],
  },
  {
    state: 'Jharkhand',
    cities: [
      'Ranchi',
      'Jamshedpur',
      'Dhanbad',
      'Bokaro Steel City',
      'Deoghar',
      'Hazaribagh',
      'Giridih',
    ],
  },
  {
    state: 'Chhattisgarh',
    cities: [
      'Raipur',
      'Bhilai',
      'Bilaspur',
      'Korba',
      'Durg',
      'Rajnandgaon',
      'Jagdalpur',
    ],
  },
  {
    state: 'Uttarakhand',
    cities: [
      'Dehradun',
      'Haridwar',
      'Roorkee',
      'Haldwani',
      'Rudrapur',
      'Rishikesh',
      'Kashipur',
    ],
  },
  {
    state: 'Goa',
    cities: ['Panaji', 'Margao', 'Vasco da Gama', 'Mapusa', 'Ponda'],
  },
  {
    state: 'Himachal Pradesh',
    cities: ['Shimla', 'Dharamshala', 'Solan', 'Mandi', 'Kullu', 'Hamirpur'],
  },
  {
    state: 'Jammu & Kashmir',
    cities: ['Srinagar', 'Jammu', 'Anantnag', 'Baramulla', 'Udhampur'],
  },
  {
    state: 'Chandigarh',
    cities: ['Chandigarh'],
  },
  {
    state: 'Puducherry',
    cities: ['Puducherry', 'Karaikal'],
  },
];
